### PR TITLE
Main linker refactor: pure linker, using paths instead of object refs and defining scopes top-down

### PR DESCRIPTION
**Pull request by javierfernandes**
This refactors changes the way we link objects to avoid cloning references now that the linker is (almost) pure.

Instead of having scopes like this

```json
 {
    "type": "aNode",
    "scope": {
        "a": <a Node >
        "b": <a Node >
    }
```

and instead of having links like this:

```json
{
    "type": "Reference"
    "name": {
        "type": "Ref"
        "node": < a node >
    }
}
```

We now use "paths".

```json
 {
    "type": "aNode",
    "scope": {
        "a": ["root", "content", "sentences", "sentences[1]"]
        "b": ["root", "content", "sentences", "sentences[3]", "thenSentence", "sentences[2]" ]
    }
```

and instead of having links like this:

```json
{
    "type": "Reference"
    "name": {
        "type": "Link": {
        "token": "a",
        "path": ["root", "content", "sentences", "sentences[1]"]
    }
}
```

I have renamed the "Ref" node to be "Link" and a link has a token (original text) and a path.
You can later resolve a path with a function from `scoping.js` with signature `resolvePath(nodes, path)`

I have also refactored the way scopes are created: instead of finding a variable/parameter/field and registering on its parent scope (bottom-up), which meant to mutate a node that was not "the current" rendering incompatible with the "pure transformation model", now it does it top-down.
When it finds a node it creates its scope.
For that now the definitions have changed:

```js
/* nodes that define new scopes/namespaces */
export const scopes = {
  [File]: _ => _.content,
  [Module]: _ => _.members.filter(m => m.is(Field)),
  [Method]: _ => _.parameters,
  [Closure]: _ => _.parameters,
  [Block]: _ => _.sentences.filter(s => s.is(VariableDeclaration))
}
```

Also they now use "categories". Each key hast the type/category and a function to return an array of elements representing the scope.

This means that we actually don't need the "parent" relation to create links. 
Although we still have them because they are being used for later resolving the `path-based links` into real object references (for example in the compiler)

We need to rethink that step as something "out of the linker".

### CODE REVIEW

**Comment by javierfernandes** [comment]
A path has basically the property access path to get to that node.
Path: 

```
    property[index]
```
Where index is optional and only for array properties.

**Comment by javierfernandes** [comment]
As a side-effect I had to disable the checking of link types (for example that you link to a Class for superclass and not another "thing").
This is because the link now is a path that doesn't include the target object type.
I didn't want to make it complex.
So the type checking could be a separated step

**Comment by javierfernandes** [comment]
@nscarcella I was able to do the change that we mentioned today.
So the output of the linker now doesn't have circular references for links.
And to to the linking it doesn't produce mutations.

But..... this is not 100% true.
The only remaining mutation is now with "parent". All nodes have the parent, which (was a circular reference, but now that nodes are copied ...) create copy of parent objects.
This are actually not needed to do the linking, if we now consider linking as the process of creating "paths" like ids and pointers to ids.
But, they are need for a "post-processing" of those path-based links, to actually resolve those paths to real objects.

This is used currently from the compiler.
And it is working just because they nodes have the parents, But I'll like to remove them !

For the internals of the linker, to avoid using the parent for linking paths I had to include the context on the visiting to each node, to be able to access all the parents.
But I cannot do that from the compiler, since the API for traverse is different.

Any idea on how we can do this ?
The thing is that on any particular node we need to resolve a path. Having access to the root node (besides the current one) would be enough, I guess.

If we accomplish that, then the linker would be 100% pure and with a defined output structure, simpler and without circular references, or redundant data. :)

**Comment by nscarcella** [comment]
Looks good, go ahead and merge it.

Regarding the compiler thing with the parent I don't fully understand the problem. Can you point me to it on the code?

**Pull request merged**
