### PR TITLE
Splitting model into small files. Reusing code between literals

### PR DESCRIPTION
**Pull request by javierfernandes**
Let me know what do you think about this ?

I understand that having it in a single file sometimes has its benefits, but also having separated files has another pros :P like using the filesystem to organize the code, finding by file name, avoiding comments separators, etc..

Also notice that I introduced some higher-order fn to reuse code in literals

```js
const ValueLiteral = name => value => Node(`${name}Literal`)({ value })
export const BooleanLiteral = ValueLiteral('Boolean')
export const NumberLiteral = ValueLiteral('Number')
export const StringLiteral = ValueLiteral('String')

const ValuesLiteral = name => (...values) => Node(`${name}Literal`)({ values })
export const SetLiteral = ValuesLiteral('Set')
export const ListLiteral = ValuesLiteral('List')
```

### CODE REVIEW

**Comment by nscarcella** [comment]
Looks good, although it makes me wonder if we need separate nodes for each literal type or we could just throw those away and have a single node with a composed literalType. What do you think @javierfernandes ?

**Comment by nscarcella** [comment]
Also, whatever codeclimate is, it doesn't seem to be happy :P

**Comment by javierfernandes** [comment]
Yes, I don't mind unifying literals, as long as we have some way to type them.
I was actually trying to understand how can we do some kind of "pattern-matching" of the AST for processing it.

I understand that you use functions and high-level functions instead of classes for the model. That ressembles scala case-classes :) which is cool and we can see how easy it is to manipulate those nodes for example for comparing in tests (expects equals).

But what about later when visiting the ast to do things (like linking, validating, interpreting, etc..) Do you have something in mind already ?

We can talk about this later better, but I had this crazy idea of coding an interpreter in a functional way, like redux store and actions. Modeling state changes as monads (?) taking the current state and producing a new state, instead of mutating.

This could be really powerful for debugging and also to develop an effect-system on top of it.
The interpreter itself would perform discrete steps with `state => newstate`.
Anyway, this is probably something to think better, just wanted to throw the idea :P

(i'm trying to fix codeclimate.. it is just a service to analyze the code for coverage and stuff)

**Comment by javierfernandes** [comment]
Merging it to allow further changes ASAP as it is a disruptive change (moving files around)

**Comment by nscarcella** [comment]
@javierfernandes 

> But what about later when visiting the ast to do things (like linking, validating, interpreting, etc..) Do you have something in mind already ?

> We can talk about this later better, but I had this crazy idea of coding an interpreter in a functional way, like redux store and actions. Modeling state changes as monads (?) taking the current state and producing a new state, instead of mutating.

HAHAHA you read my mind!

The current node representation was just a temporal thing. Was hoping to get a better idea of how to represent the nodes once we were handling them. That's the main reason I created those factory functions, so we can easily replace the representation without having to change all the grammar and tests.

One option would be to use ES6 classes for the nodes, but it didn't seem to add much at the moment... Sadly ES has nothing remotely like pattern matching. It would be SOOOOO good to have Scala's case classes for this...

There are a couple of libraries out there like [https://github.com/natefaubion/sparkler](https://github.com/natefaubion/sparkler) and [https://github.com/sweet-js/sweet-core](https://github.com/sweet-js/sweet-core) that do something like pattern matching, but I'm not sure if it's worth the effort. Seems like a nice approach, but not sure how maintained those libraries are or how big the overhead would be... Also I get easily distracted and may loose the way home :p

Perhaps the best course of action is build a working vanilla implementation and add the crazy improvements later on, so we can also compare them in terms of performance and maintainability.

**Pull request merged**
