### PR TITLE
Linker refactor: support linking attributes instead of whole nodes

### PR DESCRIPTION
**Pull request by javierfernandes**
Changes:

* refactor on the linker to support linking node "attributes" instead of whole nodes. This allows to have more than one link for a node type, for example Class: has "superclass" but also "mixins", which is an array of links (also new support for that)
* links declaration now specifies the node type which gets translated into a check. So there is a first "check" for this already embeded in the linker (because I believe it is a low-level basic check, very related to linking, rather than just validations).
* some other small refactors to be able to create visitors with simple functions.
* Resolved links now create a new ast node type `Ref(node)`

### CODE REVIEW

**Comment by nscarcella** [comment]
Looks good. Let's fix the linter before merging.

Do you think we should replace any of the current model attributes to store a Ref instead? Perhaps Variable should be replaced with this, or the fields that store a "class name"?

Also, perhaps we should move the Ref definition to the model file.

**Comment by javierfernandes** [comment]
Merged and all tests running fine.
I don't like the code that I had to change in the compiler for variable resolution, but it works :P

@nscarcella take a look at how "definitions.js" looks now for describing the "linkables".
I still need to work on the other definitions (like I would like to infer the "referenciables, from the "linkables", and maybe express the scopes in some other way, not so magical. 
Something like

```
const scopes = {
    Class: c => c.members.filter(_ => _.type === 'Field)
    Closure: c => c.params
}
```

Still this would be useful for some other language with more complex scoping. Wollok is really simple in this, since it uses lexical scoping (and hierarchical, meaning always look up in the parent scope)
So, I'm not sure it is worthly to do it right now.

**Comment by nscarcella** [comment]
Sorry. Clicked by accident.
@javierfernandes Now that the transformation change is merged I think we could eventually define the linkables as model categories if you want to. That way you could use the is method and the builder without needing to turn them to strings.

Fix the conflicts and merge.

**Comment by javierfernandes** [comment]
Fixed conflicts.
Checking linter errors I see 88 warnings :(
But eslint --fix doesnt' seems to fix them.
Almost all of them are in natives.js so I just disabled the linter for that file
The remaing issues (4) are in interpreter.test.js, in some commeted out code.
Maybe it is better if you take a look at those, after merging.

Regarding "Variable" yes, I think that we need to change the name in the model to a "Reference".
Then in the linker I could use "Link" or something.
But Variable is really confusing with the variable declaration

**Pull request merged**
